spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: xxxxx@qq.com
    password: xxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true