server:
  port: 8080
spring:
  application:
    name: tk-mybatis-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn-spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xieyun520
#指定mybatis映射的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 转化日期格式
jackson:
  time-zone: GMT+8
  date-format: yyyy-MM-dd HH:mm:ss

# 打印sql日志
logging:
  level:
    com.ucmed.tkmybatis.mapper: debug