server:
  port: 8080
spring:
  #给项目来个名字
  application:
    name: rabbitmq-demo
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
    virtual-host: my_vhost
    #消息确认配置项
    ## 确认消息已发送到交换机Exchange
    publisher-confirms: true
    ##确认消息已发送到队列Queue
    publisher-returns: true

